<a href="https://colab.research.google.com/github/EdwinSanFI/Machine-Learning/blob/master/Fundamentos_Pr%C3%A1cticos_Introducci%C3%B3n_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [ ]:
a = np.array([10, 20, 30, 40, 8, 2, 40, 100])
a[4]

8

In [ ]:
 a[4:]

array([  8,   2,  40, 100])

In [ ]:
a[3:7]

array([40,  8,  2, 40])

In [ ]:
a[2::2]

array([30,  8, 40])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones = np.ones((4,5))

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
type(ones[3])

numpy.ndarray

In [ ]:
 np.linspace(3,10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [ ]:
b = np.array([['x', 'y', 'z'], ['a', 'b', 'c']])
type(b)

numpy.ndarray

In [ ]:
c = [12, 4, 18, 3, 1, 12]
np.sort(c)

array([ 1,  3,  4, 12, 12, 18])

In [ ]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42)]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [ ]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.diag([7,4,21,9])

array([[ 7,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 21,  0],
       [ 0,  0,  0,  9]])

In [ ]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])